# Don't print a new line at the start of the prompt
add_newline = false
command_timeout = 500

[username]
disabled = true
[hostname]
disabled = true
[container]
disabled = true

[line_break]
disabled = false

[directory]
truncation_length = 8       # 最长显示路径级别
truncate_to_repo = false    # 在 git 目录下不截断路径
style = "bold cyan"
read_only = " "

[kubernetes]
format = "[$context:$namespace](blue) "
disabled = false

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[env_var]
variable = "SHELL_PROXY"
format = "[$env_value](blue)  "

[cmd_duration]
min_time = 4_000              # 4000ms
show_milliseconds = true
style = "yellow"

[git_branch]
symbol = " "

[docker_context]
symbol = " "
disabled = true

[package]
symbol = " "
disabled = true

[aws]
symbol = "  "
disabled = true

[gcloud]
disabled = true

[c]
symbol = " "

[dart]
symbol = " "

[elixir]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[lua]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "
